<?php

namespace App\Repository;

/**
 * AdmiTipoClientePuntajeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdmiTipoClientePuntajeRepository extends \Doctrine\ORM\EntityRepository
{
}
