<?php

namespace App\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;
/**
 * InfoClienteEncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoClienteEncuestaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Documentación para la función 'getClienteEncuesta'
     * Método encargado de retornar las relaciones entre cliente y encuesta según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 27-09-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */    
    public function getClienteEncuesta($arrayParametros)
    {
        $strEstado          = $arrayParametros['strEstado'] ? $arrayParametros['strEstado']:array('ACTIVO','INACTIVO','ELIMINADO');
        $strMes             = $arrayParametros['strMes'] ? $arrayParametros['strMes']:'';
        $strAnio            = $arrayParametros['strAnio'] ? $arrayParametros['strAnio']:'';
        $arrayCltEncuesta   = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect      = "SELECT IE.ID_ENCUESTA, IE.TITULO,
                                IFNULL( (SELECT COUNT(*) 
                                            FROM INFO_CLIENTE_ENCUESTA ICE
                                            WHERE ICE.ENCUESTA_ID = IE.ID_ENCUESTA 
                                            AND EXTRACT(MONTH FROM ICE.FE_CREACION) = :strMes
                                            AND EXTRACT(YEAR  FROM ICE.FE_CREACION) = :strAnio
                                            GROUP BY ICE.ENCUESTA_ID) ,0) AS CANTIDAD ";
            $strFrom        = "FROM INFO_ENCUESTA IE ";
            $strWhere       = "WHERE IE.ESTADO in (:ESTADO) ";
            $objQuery->setParameter("ESTADO",$strEstado);
            $objQuery->setParameter("strMes", $strMes);
            $objQuery->setParameter("strAnio", $strAnio);
            $objRsmBuilder->addScalarResult('ID_ENCUESTA', 'ID_ENCUESTA', 'string');
            $objRsmBuilder->addScalarResult('TITULO', 'TITULO', 'string');
            $objRsmBuilder->addScalarResult('CANTIDAD', 'CANTIDAD', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere;
            $objQuery->setSQL($strSql);
            $arrayCltEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCltEncuesta['error'] = $strMensajeError;
        return $arrayCltEncuesta;
    }
    /**
     * Documentación para la función 'getClienteEncuestaSemestral'
     * Método encargado de retornar las relaciones entre cliente y encuesta semestrales 
     * según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 16-10-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */
    public function getClienteEncuestaSemestral($arrayParametros)
    {
        $strEstado          = $arrayParametros['strEstado'] ? $arrayParametros['strEstado']:array('ACTIVO','INACTIVO','ELIMINADO');
        $strLimite          = $arrayParametros['strLimite'] ? $arrayParametros['strLimite']:'';
        $arrayCltEncuesta   = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect      = "SELECT IE.ID_ENCUESTA, IE.TITULO,
                                    EXTRACT(MONTH FROM ICE.FE_CREACION) AS MES,
                                    EXTRACT(YEAR  FROM ICE.FE_CREACION) AS ANIO, 
                                    IFNULL(COUNT(*),0) AS CANTIDAD ";
            $strFrom        = " FROM INFO_CLIENTE_ENCUESTA ICE
                                    INNER JOIN INFO_ENCUESTA IE ON ICE.ENCUESTA_ID = IE.ID_ENCUESTA ";
            $strWhere       = " WHERE IE.ESTADO in (:ESTADO) ";
            $strGroup       = " GROUP BY ICE.ENCUESTA_ID,EXTRACT(MONTH FROM ICE.FE_CREACION),EXTRACT(YEAR  FROM ICE.FE_CREACION) ";
            $strOrder       = " ORDER BY ICE.FE_CREACION DESC ";
            $strLimit       = " LIMIT ".$strLimite." ";
            $objQuery->setParameter("ESTADO",$strEstado);

            $objRsmBuilder->addScalarResult('ID_ENCUESTA', 'ID_ENCUESTA', 'string');
            $objRsmBuilder->addScalarResult('TITULO', 'TITULO', 'string');
            $objRsmBuilder->addScalarResult('MES', 'MES', 'string');
            $objRsmBuilder->addScalarResult('ANIO', 'ANIO', 'string');
            $objRsmBuilder->addScalarResult('CANTIDAD', 'CANTIDAD', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere.$strGroup.$strOrder.$strLimit;
            $objQuery->setSQL($strSql);
            $arrayCltEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCltEncuesta['error'] = $strMensajeError;
        return $arrayCltEncuesta;
    }
    /**
     * Documentación para la función 'getClienteEncuestaSemanal'
     * Método encargado de retornar las relaciones entre cliente y encuesta semanal 
     * según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 16-10-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */
    public function getClienteEncuestaSemanal($arrayParametros)
    {
        $strEstado          = $arrayParametros['strEstado'] ? $arrayParametros['strEstado']:array('ACTIVO','INACTIVO','ELIMINADO');
        $strLimite          = $arrayParametros['strLimite'] ? $arrayParametros['strLimite']:'';
        $arrayCltEncuesta   = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect      = "SELECT IE.ID_ENCUESTA, 
                                IE.TITULO,
                                WEEK(ICE.FE_CREACION) AS SEMANA,
                                EXTRACT(YEAR  FROM ICE.FE_CREACION) AS ANIO, 
                                IFNULL(COUNT(*),0) AS CANTIDAD ";
            $strFrom        = " FROM INFO_CLIENTE_ENCUESTA ICE
                                    INNER JOIN INFO_ENCUESTA IE ON ICE.ENCUESTA_ID = IE.ID_ENCUESTA ";
            $strWhere       = " WHERE IE.ESTADO in (:ESTADO) ";
            $strGroup       = " GROUP BY ICE.ENCUESTA_ID,WEEK(ICE.FE_CREACION),EXTRACT(YEAR  FROM ICE.FE_CREACION) ";
            $strOrder       = " ORDER BY ICE.FE_CREACION DESC ";
            $strLimit       = " LIMIT ".$strLimite." ";
            $objQuery->setParameter("ESTADO",$strEstado);

            $objRsmBuilder->addScalarResult('ID_ENCUESTA', 'ID_ENCUESTA', 'string');
            $objRsmBuilder->addScalarResult('TITULO', 'TITULO', 'string');
            $objRsmBuilder->addScalarResult('SEMANA', 'SEMANA', 'string');
            $objRsmBuilder->addScalarResult('ANIO', 'ANIO', 'string');
            $objRsmBuilder->addScalarResult('CANTIDAD', 'CANTIDAD', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere.$strGroup.$strOrder.$strLimit;
            $objQuery->setSQL($strSql);
            $arrayCltEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCltEncuesta['error'] = $strMensajeError;
        return $arrayCltEncuesta;
    }
    /**
     * Documentación para la función 'getClienteGenero'
     * Método encargado de retornar los generos de los clientes
     * según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 16-10-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */
    public function getClienteGenero($arrayParametros)
    {
        $strMes             = $arrayParametros['strMes'] ? $arrayParametros['strMes']:'';
        $strAnio            = $arrayParametros['strAnio'] ? $arrayParametros['strAnio']:'';
        $arrayCltEncuesta   = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect      = "SELECT IC.GENERO,COUNT(*) AS CANTIDAD ";
            $strFrom        = " FROM INFO_CLIENTE_ENCUESTA ICE
                                INNER JOIN INFO_CLIENTE IC ON ICE.CLIENTE_ID = IC.ID_CLIENTE ";
            $strWhere       = " WHERE EXTRACT(MONTH FROM ICE.FE_CREACION)  = :MES
                                    AND EXTRACT(YEAR FROM ICE.FE_CREACION) = :ANIO ";
            $strGroup       = " GROUP BY IC.GENERO ";
            $objQuery->setParameter("MES",$strMes);
            $objQuery->setParameter("ANIO",$strAnio);

            $objRsmBuilder->addScalarResult('CANTIDAD', 'CANTIDAD', 'string');
            $objRsmBuilder->addScalarResult('GENERO', 'GENERO', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere.$strGroup;
            $objQuery->setSQL($strSql);
            $arrayCltEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCltEncuesta['error'] = $strMensajeError;
        return $arrayCltEncuesta;
    }
    /**
     * Documentación para la función 'getClienteEdad'
     * Método encargado de retornar las edades de los clientes
     * según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 16-10-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */
    public function getClienteEdad($arrayParametros)
    {
        $strMes             = $arrayParametros['strMes'] ? $arrayParametros['strMes']:'';
        $strAnio            = $arrayParametros['strAnio'] ? $arrayParametros['strAnio']:'';
        $arrayCltEncuesta   = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            $strSelect      = "SELECT (SELECT VALOR1 
                                            FROM ADMI_PARAMETRO
                                            WHERE DESCRIPCION = 'EDAD' 
                                            AND EXTRACT(YEAR FROM IC.EDAD) >= VALOR2 
                                            AND EXTRACT(YEAR FROM IC.EDAD) <= VALOR3) AS GENERACION,
                                        COUNT(*) AS CANTIDAD  ";
            $strFrom        = " FROM INFO_CLIENTE_ENCUESTA ICE
                                    INNER JOIN INFO_CLIENTE IC 
                                        ON ICE.CLIENTE_ID = IC.ID_CLIENTE ";
            $strWhere       = " WHERE EXTRACT(MONTH FROM ICE.FE_CREACION)  = :MES
                                    AND EXTRACT(YEAR FROM ICE.FE_CREACION) = :ANIO ";
            $strGroup       = " GROUP BY GENERACION ";
            $objQuery->setParameter("MES",$strMes);
            $objQuery->setParameter("ANIO",$strAnio);

            $objRsmBuilder->addScalarResult('CANTIDAD', 'CANTIDAD', 'string');
            $objRsmBuilder->addScalarResult('GENERACION', 'GENERACION', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere.$strGroup;
            $objQuery->setSQL($strSql);
            $arrayCltEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCltEncuesta['error'] = $strMensajeError;
        return $arrayCltEncuesta;
    }
    /**
     * Documentación para la función 'getVigenciaEncuesta'
     * Método encargado de validar si el cliente ya generó una encuesta en el día
     * según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 28-10-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */
    public function getVigenciaEncuesta($arrayParametros)
    {
        $intIdCliente       = $arrayParametros['intIdCliente'] ? $arrayParametros['intIdCliente']:'';
        $intIdSucursal      = $arrayParametros['intIdSucursal'] ? $arrayParametros['intIdSucursal']:'';
        $arrayCltEncuesta   = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        $date               = date('Y-m-d H:i:s');
        try
        {
            $strSelect      = "SELECT COUNT(*) AS CANTIDAD ";
            $strFrom        = " FROM INFO_CLIENTE_ENCUESTA ICE ";
            $strWhere       = " WHERE TIMESTAMPDIFF(HOUR,ICE.FE_CREACION,'".$date."') < 24 
                                    AND ICE.CLIENTE_ID  = :CLIENTE_ID
                                    AND ICE.SUCURSAL_ID = :SUCURSAL_ID ";
            $objQuery->setParameter("CLIENTE_ID",$intIdCliente);
            $objQuery->setParameter("SUCURSAL_ID",$intIdSucursal);

            $objRsmBuilder->addScalarResult('CANTIDAD', 'CANTIDAD', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere;
            $objQuery->setSQL($strSql);
            $arrayCltEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCltEncuesta['error'] = $strMensajeError;
        return $arrayCltEncuesta;
    }
    /**
     * Documentación para la función 'getCantPtosResEnc'
     * Método encargado de que me retorne los restaurantes que yo he comido y llenado encuestas, 
     * devolviendo adicional el puntaje por restaurante.
     * 
     * @author Kevin Baque
     * @version 1.0 28-10-2019
     * 
     * @return array  $arrayCltEncuesta
     * 
     */
    public function getCantPtosResEnc($arrayParametros)
    {
        $intIdCliente       = $arrayParametros['intIdCliente'] ? $arrayParametros['intIdCliente']:'';
        $strEstado          = $arrayParametros['strEstado'] ? $arrayParametros['strEstado']:'';
        $arrayCantPtos      = array();
        $strMensajeError    = '';
        $objRsmBuilder      = new ResultSetMappingBuilder($this->_em);
        $objQuery           = $this->_em->createNativeQuery(null, $objRsmBuilder);
        try
        {
            //SUM(ICE.CANTIDAD_PUNTOS) AS CANT_PUNTOS,
            $strSelect      = "SELECT IRE.NOMBRE_COMERCIAL,
                                      IRE.ID_RESTAURANTE,
                                      IRE.ICONO ";
            $strFrom        = " FROM INFO_CLIENTE_ENCUESTA ICE
                                JOIN INFO_SUCURSAL         ISUR ON ISUR.ID_SUCURSAL   = ICE.SUCURSAL_ID
                                JOIN INFO_RESTAURANTE      IRE  ON IRE.ID_RESTAURANTE = ISUR.RESTAURANTE_ID ";
            $strWhere       = " WHERE ICE.ESTADO  = :ESTADO
                                    AND ISUR.ESTADO = :ESTADO
                                    AND IRE.ESTADO  = :ESTADO ";
            $strGroupBy     = " GROUP BY IRE.ID_RESTAURANTE ";
            $objQuery->setParameter("ESTADO",$strEstado);
            if(!empty($intIdCliente))
            {
                $strSelect .= ", (SELECT IFNULL(SUM(ICP.CANTIDAD_PUNTOS ),0) FROM INFO_CLIENTE_PUNTO ICP WHERE CLIENTE_ID = :CLIENTE_ID AND ICP.RESTAURANTE_ID = IRE.ID_RESTAURANTE) AS CANT_PUNTOS ";
                $strWhere .= " AND ICE.CLIENTE_ID= :CLIENTE_ID ";
                $objQuery->setParameter("CLIENTE_ID",$intIdCliente);
            }

            $objRsmBuilder->addScalarResult('CANT_PUNTOS', 'CANT_PUNTOS', 'string');
            $objRsmBuilder->addScalarResult('NOMBRE_COMERCIAL', 'RAZON_SOCIAL', 'string');
            $objRsmBuilder->addScalarResult('ICONO', 'ICONO', 'string');
            $objRsmBuilder->addScalarResult('ID_RESTAURANTE', 'IDRESTAURANTE', 'string');
            $strSql       = $strSelect.$strFrom.$strWhere.$strGroupBy;
            $objQuery->setSQL($strSql);
            $arrayCantPtos['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayCantPtos['error'] = $strMensajeError;
        return $arrayCantPtos;
    }
}
