<?php

namespace App\Repository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * InfoEncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoEncuestaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Documentación para la función 'getEncuestaCriterio'
     * Método encargado de retornar todos las encuestas según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 16-07-2019
     * 
     * @return array  $arrayEncuesta
     * 
     */    
    public function getEncuestaCriterio($arrayParametros)
    {
        $strIdEncuesta         = $arrayParametros['strIdEncuesta'] ? $arrayParametros['strIdEncuesta']:'';
        $strDescripcion        = $arrayParametros['strDescripcion'] ? $arrayParametros['strDescripcion']:'';
        $strTitulo             = $arrayParametros['strTitulo'] ? $arrayParametros['strTitulo']:'';
        $strContador           = $arrayParametros['strContador'] ? $arrayParametros['strContador']:'NO';
        $strEstado             = $arrayParametros['strEstado'] ? $arrayParametros['strEstado']:array('ACTIVO','INACTIVO','ELIMINADO');
        $arrayEncuesta         = array();
        $strMensajeError       = '';
        $objRsmBuilder         = new ResultSetMappingBuilder($this->_em);
        $objQuery              = $this->_em->createNativeQuery(null, $objRsmBuilder);
        $objRsmBuilderCount    = new ResultSetMappingBuilder($this->_em);
        $objQueryCount         = $this->_em->createNativeQuery(null, $objRsmBuilderCount);
        $strOrder           = ' ORDER BY EC.FE_CREACION ASC';
        try
        {
            if(!empty($strContador) && $strContador == 'SI')
            {
                $strSelectCount = "SELECT COUNT(*) AS CANTIDAD ";
                $strFromCount   = "FROM INFO_ENCUESTA EC ";
                $strWhereCount  = "WHERE EC.ESTADO in (:ESTADO) ";
                $objQueryCount->setParameter("ESTADO", $strEstado);
                $objRsmBuilderCount->addScalarResult('CANTIDAD', 'Cantidad', 'integer');
                $strSqlCount  = $strSelectCount.$strFromCount.$strWhereCount;
                $objQueryCount->setSQL($strSqlCount);
                $arrayEncuesta['cantidad']   = $objQueryCount->getSingleScalarResult();
            }
            else
            {
                $strSelect      = "SELECT EC.ID_ENCUESTA,EC.DESCRIPCION,EC.TITULO,EC.ESTADO AS ESTADO_ENCUESTA, 
                                EC.USR_CREACION, EC.FE_CREACION,EC.USR_MODIFICACION,EC.FE_MODIFICACION ";
                $strFrom        = "FROM INFO_ENCUESTA EC ";
                $strWhere       = "WHERE EC.ESTADO in (:ESTADO) ";
                $objQuery->setParameter("ESTADO", $strEstado);

                if(!empty($strIdEncuesta))
                {
                    $strWhere .= " AND EC.ID_ENCUESTA =:ID_ENCUESTA";
                    $objQuery->setParameter("ID_ENCUESTA", $strIdEncuesta);
                }
                if(!empty($strDescripcion))
                {
                    $strWhere .= " AND lower(EC.DESCRIPCION) like lower(:DESCRIPCION)";
                    $objQuery->setParameter("DESCRIPCION", '%' . trim($strDescripcion) . '%');
                }
                if(!empty($strTitulo))
                {
                    $strWhere .= " AND lower(EC.TITULO) like lower(:TITULO)";
                    $objQuery->setParameter("TITULO", '%' . trim($strTitulo) . '%');
                }
                $objRsmBuilder->addScalarResult('ID_ENCUESTA', 'ID_ENCUESTA', 'string');
                $objRsmBuilder->addScalarResult('DESCRIPCION', 'DESCRIPCION', 'string');
                $objRsmBuilder->addScalarResult('TITULO', 'TITULO', 'string');
                $objRsmBuilder->addScalarResult('ESTADO_ENCUESTA', 'ESTADO_ENCUESTA', 'string');
                $objRsmBuilder->addScalarResult('USR_CREACION', 'USR_CREACION', 'string');
                $objRsmBuilder->addScalarResult('FE_CREACION', 'FE_CREACION', 'date');
                $objRsmBuilder->addScalarResult('USR_MODIFICACION', 'USR_MODIFICACION', 'string');
                $objRsmBuilder->addScalarResult('FE_MODIFICACION', 'FE_MODIFICACION', 'date');

                $strSql       = $strSelect.$strFrom.$strWhere;
                $objQuery->setSQL($strSql);
                $arrayEncuesta['resultados'] = $objQuery->getResult();
            }
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayEncuesta['error'] = $strMensajeError;
        return $arrayEncuesta;
    }
    
    /**
     * Documentación para la función 'getEncuestaCriterioMovil'
     * Método encargado de retornar todos las encuestas según los parámetros recibidos.
     * 
     * @author Kevin Baque
     * @version 1.0 02-09-2019
     * 
     * @return array  $arrayEncuesta
     * 
     */
    public function getEncuestaCriterioMovil($arrayParametros)
    {
        $strIdRestaurante      = $arrayParametros['strIdRestaurante'] ? $arrayParametros['strIdRestaurante']:'';
        $strIdEncuesta         = $arrayParametros['strIdEncuesta'] ? $arrayParametros['strIdEncuesta']:'';
        $strDescripcion        = $arrayParametros['strDescripcion'] ? $arrayParametros['strDescripcion']:'';
        $strTitulo             = $arrayParametros['strTitulo'] ? $arrayParametros['strTitulo']:'';
        $strEstado             = $arrayParametros['strEstado'] ? $arrayParametros['strEstado']:array('ACTIVO','INACTIVO','ELIMINADO');
        $arrayEncuesta         = array();
        $strMensajeError       = '';
        $objRsmBuilder         = new ResultSetMappingBuilder($this->_em);
        $objQuery              = $this->_em->createNativeQuery(null, $objRsmBuilder);
        $objRsmBuilderCount    = new ResultSetMappingBuilder($this->_em);
        $objQueryCount         = $this->_em->createNativeQuery(null, $objRsmBuilderCount);
        $strOrder           = ' ORDER BY EC.FE_CREACION ASC';
        try
        {
            $strSelect      = "SELECT EC.ID_ENCUESTA,EC.DESCRIPCION,EC.TITULO,EC.ESTADO AS ESTADO_ENCUESTA, 
                                      EC.USR_CREACION, EC.FE_CREACION,EC.USR_MODIFICACION,EC.FE_MODIFICACION ";
            $strSelectCount = "SELECT COUNT(*) AS CANTIDAD ";
            $strFrom        = "FROM INFO_ENCUESTA EC ";
            $strWhere       = "WHERE EC.ESTADO in (:ESTADO) ";
            $objQuery->setParameter("ESTADO", $strEstado);
            $objQueryCount->setParameter("ESTADO", $strEstado);
            if(!empty($strIdEncuesta))
            {
                $strWhere .= " AND EC.ID_ENCUESTA =:ID_ENCUESTA";
                $objQuery->setParameter("ID_ENCUESTA", $strIdEncuesta);
                $objQueryCount->setParameter("ID_ENCUESTA", $strIdEncuesta);
            }
            if(!empty($strDescripcion))
            {
                $strWhere .= " AND lower(EC.DESCRIPCION) like lower(:DESCRIPCION)";
                $objQuery->setParameter("DESCRIPCION", '%' . trim($strDescripcion) . '%');
                $objQueryCount->setParameter("DESCRIPCION", '%' . trim($strDescripcion) . '%');
            }
            if(!empty($strTitulo))
            {
                $strWhere .= " AND lower(EC.TITULO) like lower(:TITULO)";
                $objQuery->setParameter("TITULO", '%' . trim($strTitulo) . '%');
                $objQueryCount->setParameter("TITULO", '%' . trim($strTitulo) . '%');
            }
            $objRsmBuilder->addScalarResult('ID_ENCUESTA', 'ID_ENCUESTA', 'string');
            $objRsmBuilder->addScalarResult('DESCRIPCION', 'DESCRIPCION', 'string');
            $objRsmBuilder->addScalarResult('TITULO', 'TITULO', 'string');
            $objRsmBuilder->addScalarResult('ESTADO_ENCUESTA', 'ESTADO_ENCUESTA', 'string');
            $objRsmBuilder->addScalarResult('USR_CREACION', 'USR_CREACION', 'string');
            $objRsmBuilder->addScalarResult('FE_CREACION', 'FE_CREACION', 'date');
            $objRsmBuilder->addScalarResult('USR_MODIFICACION', 'USR_MODIFICACION', 'string');
            $objRsmBuilder->addScalarResult('FE_MODIFICACION', 'FE_MODIFICACION', 'date');

            $objRsmBuilderCount->addScalarResult('CANTIDAD', 'Cantidad', 'integer');
            $strSql       = $strSelect.$strFrom.$strWhere;
            $objQuery->setSQL($strSql);
            $strSqlCount  = $strSelectCount.$strFrom.$strWhere.$strOrder;
            $objQueryCount->setSQL($strSqlCount);
            $arrayEncuesta['cantidad']   = $objQueryCount->getSingleScalarResult();
            $arrayEncuesta['resultados'] = $objQuery->getResult();
        }
        catch(\Exception $ex)
        {
            $strMensajeError = $ex->getMessage();
        }
        $arrayEncuesta['error'] = $strMensajeError;
        return $arrayEncuesta;
    }
}
