<?php

namespace App\Repository;

/**
 * InfoContenidoSubidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoContenidoSubidoRepository extends \Doctrine\ORM\EntityRepository
{
}
