<?php

namespace App\Repository;

/**
 * InfoLikeResRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoLikeResRepository extends \Doctrine\ORM\EntityRepository
{
}
