<?php

namespace App\Repository;

/**
 * InfoClientePuntoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoClientePuntoRepository extends \Doctrine\ORM\EntityRepository
{
}
