<?php

namespace App\Repository;

/**
 * InfoClientePuntoGlobalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoClientePuntoGlobalRepository extends \Doctrine\ORM\EntityRepository
{
}
